### ISSUE TITLE
Webpack development mode

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-cli#1987]
We want to support webpack while developing (Angular) apps. The goal is to both reduce the app bundle size and provide livesync support.
- [x] Allow the WebPack to control how the CLI will handle app and plugin resources #1984
- [ ] Spawn webpack-dev-server and watch for changes
- [ ] (Sync 1) Listen for module changes on the device (similar to the socket.io + karma approach)
- [ ] (Sync 2) Trigger device sync after bundle update (by the webpack dev server)
- [x] Split the bundle into vendor and app chunks and update just the app one (faster). Keep the production bundle as one file though -- required by the snapshot tool.
- [x] Evaluate build performance and come up with sourcemaps, typechecking options. Configure awesome-typescript-loader's out-of-process typechecker.
- [ ] Introduce a separate production build with different sourcemap settings, dedupe plugin. Single file to enable snapshots.
- [x] How will this affect debugging?
- [ ] Plugin support - we need both a generic plugin bundling solution and a hook for plugs to expose their own webpack options, which we can merge with [webpack-merge](https://www.npmjs.com/package/webpack-merge)

Sync 1 and 2 above seem mutually exclusive. We have two options when upddating the app: sync files and restart (option 2) and let webpack do its hot reload thing (option 2). Option 2 will use [angular2-hmr](https://www.npmjs.com/package/angular2-hmr) which bootstrap the Angular app on hot reload and requires that you structure your app data store in a certain way.

---

Memo: 10. Aug. 2016

tns run... what do we hand-over to WebPack?

What do we do with script assets in the **app** folder?
These go into the bundle:
- .html, .js, .ts

These are copied:
- .png, .jpg, .css

Plugins will have their .js handled by WebPack when WebPack is enabled in the app. Resources:
- If the plugins have webpack config no resources should be copied for the plugin and WebPack will handle the resources.
- If the plugins have no webpack config their resources (.xml, .html, etc.) will be copied for backward compatibility.

What do we do with native code?
- Info.plist, AndroidManifest.xml, jar, aar, .framework, .a, .so etc. etc. from <plugin>/platform is processed as it is now
- Resolving dependencies in the CLI has some issues and is somewhat slow, we can try to improve it. The dependency resolution mechanism will in no way be integrated with the WebPack for now. The prepare will be split in two:
  - Prepare scripts following the existing rules, moving them to tns_modules, but this step should be be easily configured by the WebPack plug-in, to filter any .ts, .js, etc files.
  - Prepare the native part of the plugins, processing Info.plists, .aar, etc. Should support incremental builds.

**Comment by blagoev** [comment]
Some questions: 
* How are we going to reduce app bundle size with webpack (Presumably we need to pack everything in app dir, so no tree shaking etc)?

* Webpack hot reloading may be working very good for web stuff, but what about other stuff that needs to be monitored for livesync. Talking about native content/configuration/permissions/build files/resources/manifests that webpack is not designed to handle and needs app restart to be applied on the device?

* How webpack dev mode is going to reflect on non angular {N} apps dev mode? (ie Are we going to support two ways to compile Typescirpt or we are going to use awesome-typescript-loader for that as well)

**Comment by hdeshev** [comment]
> How are we going to reduce app bundle size with webpack (Presumably we need to pack everything in app dir, so no tree shaking etc)?

Even without tree shaking, non-imported modules will not get bundled. The [Dedupe plugin](https://webpack.github.io/docs/list-of-plugins.html#dedupeplugin) might help too.


> Webpack hot reloading may be working very good for web stuff, but what about other stuff that needs to be monitored for livesync. Talking about native content/configuration/permissions/build files/resources/manifests that webpack is not designed to handle and needs app restart to be applied on the device?

I think we should focus on reloading modules, markup, CSS, and images. Restarting the app after a manifest change should be perfectly fine. Or am I completely wrong here?

> How webpack dev mode is going to reflect on non angular {N} apps dev mode? (ie Are we going to support two ways to compile Typescirpt or we are going to use awesome-typescript-loader for that as well)

`nativescript-dev-typescript` should continue to work as before, but it will not make sense to use it together with webpack. It would be nice to slowly push it back and eventually deprecate it. I believe the webpack loader solution is more extensible since you can easily plug any transpiler in there. We can also benefit from stuff already implemented in `awesome-typescript-loader` such as module caching and out-of-process typechecking instead of reimplementing it eventually in `nativescript-dev-typescript`. Finally webpack-based builds are familiar to web developers, which should make those people feel right at home.

**Comment by blagoev** [comment]
My concern is if we need to bundle everything for .navigate() to work. But that may not be relevant for angular apps.

For restarting on native changes who is going to do it. Which entity will listen for these or there will be no support for that when hot reloading is used?

For non angular apps we will use webpack or webpack infrasctructure only? (So we can depreciate the plugins that exist today)?

Webpack is cool, I just hope we can leverage it correctly and fully so we indeed benefit from it.

**Comment by hdeshev** [comment]
> My concern is if we need to bundle everything for .navigate() to work. But that may not be relevant for angular apps.

The navigation issue needs to be solved, yes. We've had several halfhearted attempts at that, but maybe we should try something bigger - like navigating to JS objects instead of module file paths (we already have that), and building webpack loader(s) that create those objects from `require("mypage.xml")` imports.

> For restarting on native changes who is going to do it. Which entity will listen for these or there will be no support for that when hot reloading is used?

I wonder if we could extend the webpack build pipeline for that (research needed). My thinking here is that the webpack build can trigger a nativescript-cli action that restarts the app.

> For non angular apps we will use webpack or webpack infrasctructure only? (So we can depreciate the plugins that exist today)?

Plugins need more research too. Adding that to the list above. I believe we can come up with a generic plugin packing solution that should be able to pack most plugins. We can also provide hooks for plugins to expose their own webpack settings, and auto-merge them with [webpack-merge](https://www.npmjs.com/package/webpack-merge)

**Comment by jasssonpet** [comment]
> Split the bundle into vendor and app chunks and update just the app one.

If we are going to snapshot the bundled output, it should be a single script. That's what the V8 mksnapshot tool takes. Maybe stick to a single file in release builds?

**Comment by hdeshev** [comment]
> Maybe stick to a single file in release builds?

Great point. Adding it to the list above.

**Comment by ignaciolarranaga** [comment]
@hdeshev let me suggest also review the plugins to verify they support webpack

Right now having a problem with this (https://github.com/NativeScript/nativescript-imagepicker/issues/43) but almost any plugin I tried had something to fix.

**Comment by ignaciolarranaga** [comment]
Just noticed the issue was already identified:

> My concern is if we need to bundle everything for .navigate() to work. But that may not be relevant for angular apps.
> The navigation issue needs to be solved, yes. We've had several halfhearted attempts at that, but maybe we should try something bigger - like navigating to JS objects instead of module file paths (we already have that), and building webpack loader(s) that create those objects from require("mypage.xml") imports.

Is there any workaround ?

**Comment by NathanWalker** [comment]
@hdeshev curious on `(Sync 2) Trigger device sync after bundle update (by the webpack dev server)` - is that possible today?  What I use: `tns run ios --emulator --bundle`?  Should that auto refresh the app when a file change is triggered, causing it to rebundle then reload app in simulator?

**Comment by hdeshev** [comment]
@NathanWalker nope. We had a proof of concept, but no "production" work has been done there yet.

**Comment by maximusk** [comment]
I'm curios how does this proof of concept look? Can you please elaborate?

**Comment by sis0k0** [comment]
Webpack can now be used with livesync. HMR is on the roadmap for {N} 5.0. Closing in favor of https://github.com/NativeScript/NativeScript/issues/6398.
