### ISSUE TITLE
Predictable LiveSync/HotReload

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/nativescript-cli#2153]
The main purpose of LiveSync (hot reload) is to enable faster development time and easier try/fail type of software development. This means that the ultimate/ideal solution will have the following characteristics:
- [ ] Will sync all the code (JS/CSS/XML and HTML) and assets (images and other non-code resources outside App_Resources) in fast time (under 1 sec). This means sync for all the operations -add/update/delete of assets/code.
   - [ ] Fast sync code (JS/CSS/XML)
   - [x] Fast sync images #2277
- [x] Logging/profiling/debugging experience should be the same as if no livesync is done

In 2.5 release(TBD) :
- [x] Will display runtime errors in the app and will be able to recover from the error state without the need of restart/redeploy. Or if not possible in some cases it should be very VISIBLE for the user that he need to restart the livesync session.
- [x] If it is not technically achievable to perform fast sync for a particular app change it will restart or even re-deploy the app if needed, but will not leave a change in the app skipped (not synchronized) with the target device (emulator or physical no matter)
    - [x] Support plugin development when using the watch option #2276
    - [x] Support symlinks in app and node modules folder #2221

Not planned:
- [x] Will work together with the debugger (see https://github.com/NativeScript/nativescript-vscode-extension/issues/78)
- [x] Fast sync for images? @tzraikov ?
- [ ] Will keep the app state #2814 
- [ ] Working with AppBuilder and cloud-based emulators
- [x] Plugins development should be able to be performed using livesync
- [ ] It should be possible to livesync multiple devices and OTA.

**Comment by sis0k0** [comment]
Most of the items are either implemented or obsolete in the context of {N} 4. Closing in favor of https://github.com/NativeScript/NativeScript/issues/6398.
