### ISSUE TITLE
Remove fibers from CLI and use async/await

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/nativescript-cli#2204]
CLI uses [fibers](https://www.npmjs.com/package/fibers) in order to use sync code instead of callbacks. Fibers are great, but most of the people are not familiar with them. Also Promises are more popular now and they are integrated in Node.js. 
TypeScript allows using async/await for getting Promises results instead of chaining `.then`.
Here are the steps to be taken when fibers are removed and async/await is used instead:
- [x] Drop support for Node.js 0.12 (Deprecated in 2.4) PRs: https://github.com/telerik/mobile-cli-lib/pull/851 , https://github.com/NativeScript/nativescript-cli/pull/2320
- [x] Transpile to ES6 instead of ES5. TypeScript's async/await support is available when transpiling to ES6. PRs: https://github.com/telerik/mobile-cli-lib/pull/843 , https://github.com/NativeScript/nativescript-cli/pull/2323
- [x] Use sync API for Node core modules, like `fs` and `child_process`. Currently CLI uses async versions of the methods and wraps them with futures. In case they are replaced with Promises, each method that uses such method will have to be marked as async. However in case we use the sync versions of the methods (for example use `fs.existsSync` instead of `fs.exists` in CLI's [file-system.ts](https://github.com/telerik/mobile-cli-lib/blob/master/file-system.ts)). This way some of methods, which should be marked as `async`, will become absolutely synchronous and we'll not have to `await` them. PRs: https://github.com/telerik/mobile-cli-lib/pull/853, https://github.com/NativeScript/nativescript-cli/pull/2347 
- [ ] Fix hooks which use $fs, $childProcess, etc. as the code of the methods is changed.
- [x] Replace fibers with async/await in [mobile-cli-lib](https://github.com/telerik/mobile-cli-lib): PR: https://github.com/telerik/mobile-cli-lib/pull/865 , 
- [x] Replace fibers with async/await in nativescript-cli: https://github.com/NativeScript/nativescript-cli/pull/2411
- [x] Replace fibers with async/await in ios-sim-portable: https://github.com/telerik/ios-sim-portable/pull/83
- [ ] Test with Node.js 4
- [ ] Test with Node.js 6
- [ ] Test with Node.js 7
