### ISSUE TITLE
[Tracking] iOS App Extensions

### ISSUE THREAD

**Issue by KristianDD** [NativeScript/nativescript-cli#4472]
## Overview
iOS App Extensions feature enables adding extension via NativeScript plugins or with adding `extensions` folder inside `App_Resources/iOS/`.

The extension should be created and developed inside Xcode. Once the user is happy with the result, the folder containing the extension should be copied inside `App_Resources/iOS/extensions`. The an `extension.json` should be added. This file describes the SDK frameworks used in the extension and the  `assetcatalogCompilerAppiconName`. For example:
```JSON
{
    "frameworks": ["NotificationCenter.framework"],
    "assetcatalogCompilerAppiconName": "AppIconExtension"
}  
```

Each folder inside `App_Resources/iOS/extensions` is considered a separate extension and the folder name is considered the extension name.

### Known issues
- [ ] The extensions inside NativeScript application support only `Automatic` code signing. Any provision configuration inside `App_Resources/iOS/build.xcconfig` will be ignored. And the application build will most probably fail.
- [ ] Currently including multiple extensions using the same SDK framework is not supported.

## Discussion
Please, don't report problems here. Instead, open a new issue and link it to this one.
Let's use this discussion for suggestions and improvement ideas. We would love to hear from you!

**Comment by NickIliev** [comment]
- [x] Documentation added via https://github.com/NativeScript/docs/pull/1608

**Comment by mrpaaske** [comment]
Any progress on this feature? I'd love to be able to configure build settings for the extension as well :)

**Comment by mrpaaske** [comment]
@NickIliev, do you have some info about status and plans to complete this feature?

**Comment by mrpaaske** [comment]
@KristianDD @rosen-vladimirov Is there any progress on this task? It would be very useful to be able to have a `build.xcconfig` under `App_Resources/iOS/extensions/myext/build.xcconfig`. For example to set up manual signing, and other parameters that are local to the extension.

**Comment by romandragan** [comment]
Also extremely waiting for the ability to configure signing options of the extension.
