### ISSUE TITLE
[Tracking] Embedding Apple Watch App inside NativeScript App

### ISSUE THREAD

**Issue by KristianDD** [NativeScript/nativescript-cli#4589]
## Overview
Apple Watch App feature enables embedding a watch app in NativeScript application by adding `watchapp` and `watchextension` folders inside `App_Resources/iOS/`.

The watch app should be created and developed inside Xcode. Once the user is happy with the result, the folder containing the watch app and the watch app extension should be copied inside `App_Resources/iOS/watchapp` and `App_Resources/iOS/watchextension` respectively. Optionally you can add `watchapp.json` and `extension.json` which support multiple configurations for the build of the watch app and watch app extension.
Example JSON file:
```JSON
{
    "assetcatalogCompilerAppiconName": "AppIcon",
    "targetBuildConfigurationProperties": {
        "WATCHOS_DEPLOYMENT_TARGET": 4.1
    }
}
```
In the example above you should have an `.xcassets` catalog with `AppIcon.appiconset` inside the watchapp folder.

More information can be found in the feature issue [here](https://github.com/NativeScript/nativescript-cli/issues/4541).

### Known issues
- [ ] The watch app inside NativeScript application support only `Automatic` code signing. Any provision configuration inside `App_Resources/iOS/build.xcconfig` will be ignored. And the application build will most probably fail.
- [ ] Local frameworks (not SDK ones) will not be included in the build of the watch app.
- [ ] Single watch app can be added to the project.

## Discussion
Please, don't report problems here. Instead, open a new issue and link it to this one.
Let's use this discussion for suggestions and improvement ideas. We would love to hear from you!

**Comment by gabrielbiga** [comment]
The build just broke in favor of xrOS.
Details here: https://github.com/NativeScript/ios/issues/249
