### ISSUE TITLE
[Tracking] Support for Xcode 11 and iOS 13

### ISSUE THREAD

**Issue by Fatme** [NativeScript/nativescript-cli#4909]
## Overview
[Xcode 11](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_4_release_notes) and [iOS 13](https://developer.apple.com/documentation/ios_ipados_release_notes/ios_ipados_13_beta_4_release_notes)  bring a lot of new features and improvements, so NativeScript CLI should be able to install, run, debug and livesync applications with Xcode 11 on iOS 13 devices. 

## Tasks
- [x] Run applications on iOS 13 devices - https://github.com/NativeScript/nativescript-cli/issues/4741
- [x] Publish applications with Xcode 11 - https://github.com/NativeScript/nativescript-cli/issues/4908
- [x] Support for `.xcframework` with Xcode 11 - https://github.com/NativeScript/nativescript-cli/issues/4906
- [x] Prepare project fails - https://github.com/NativeScript/nativescript-cli/issues/4934
- [x] Launch images are deprecated in iOS 13.0 - https://github.com/NativeScript/nativescript-cli/issues/4938
- [x] CFBundleIdentifier value must be the same as PRODUCT_BUNDLE_IDENTIFIER - https://github.com/NativeScript/nativescript-cli/issues/4939
- [x] 'UILaunchImages' has been deprecated, use launch storyboards instead - https://github.com/NativeScript/nativescript-cli/issues/4940

## Known issues
- [ ] `tns doctor` throws an error when Xcode 11 is set as default and license agreement is not accepted
- [ ] Unable to mount developer disk image on locked device. The error is:
```
Failed to mount DDI from
'<DVTFilePath:0x7faea1e97280:'/Applications/Xcode-beta-11.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/13.0/DeveloperDiskImage.dmg'>',
error=-402652958: Error Domain=com.apple.dtdevicekit Code=-402652958 "Development cannot be enabled while your device is locked.
```
- [x] cannot deploy on iOS10 - https://github.com/NativeScript/nativescript-cli/issues/4956

## Discussion
Please, don't report problems here. Instead, open a new issue and link it to this one.
Let's use this discussion for suggestions and improvement ideas. We would love to hear from you!

**Comment by rosen-vladimirov** [comment]
Acceptance criteria:
- [ ] Run apps (build, deploy and livesync) on iOS 13 device/simulator with Xcode 11 on macOS Mojave
- [ ] Run apps (build, deploy and livesync) on iOS 13 device/simulator with Xcode 11 on macOS Catalina
- [ ] Run apps (build, deploy and livesync) on iOS 9 device with Xcode 10 on macOS Mojave
- [ ] Debug apps (build, deploy, stop on breakpoint, livesync and stop again) on iOS 13 device/simulator with Xcode 11 on macOS Mojave
- [ ] Debug apps (build, deploy, stop on breakpoint, livesync and stop again) on iOS 13 device/simulator with Xcode 11 on macOS Catalina
- [ ] Debug apps (build, deploy, stop on breakpoint, livesync and stop again) on iOS 9 device with Xcode 10 on macOS Mojave
- [ ] `tns cloud run` should work on Windows
- [ ] Run/Debug within Sidekick should work on Windows
