### ISSUE TITLE
Release Story - Walking up the Last Mile to the Store

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-cli#649]
Once you are done developing you app, the CLI should allow you to easily pack apk/ipa ready for submission to the store.

For iOS this involves at least two things to be automated:
 - Exporting an archive, that later can be signed with distribution certificates and submitted to the store.
 - Sign and submit to the store directly from the command-line.

The first will be more useful for larger organizations whit more strict security policies. It should create an Xcode archive that later can be opened in the Xcode organizer and submitted manually through the Xcode UI. The archive also contains app that can be signed and submitted to the AppStore from the command-line by more advanced users.

The second will be more useful for indie developers and small companies with less Bureaucracy that are ok to keep the distribution certificates in their keychain. It will also be useful for automated builds to submit automatically (similar to Telerik's companion app build). It would be extremely useful if this logs detailed distribution certificate and provisioning profile problems.

We need this elaborated for android.

---
### Related iOS issues
 - [x] hello-world app should be submittable at the AppStore #1490
 - [x] Add a package/publish command #1172 (export to xcodearchive)
 - [ ] Change versionCode/versionName when running with --release #1118
 - [x] Support build.xcconfig in /app/App_Resource/iOS folder #558
 - [ ] Add options to build with different certificate/provisioning #635

### Android
 - [x] Supports `--key-store` options which is enough to produce APK ready for submission

**Comment by ligaz** [comment]
Having https://github.com/NativeScript/nativescript-cli/issues/558 in place will allow developers to sign the app with a given certificate. Ability to publish from the Command-Line is doable by directly invoking the iTMSTransporter command line executable. 

Regarding Android [there is already a gradle plugin](https://github.com/Triple-T/gradle-play-publisher) that does the publishing.

**Comment by lscown** [comment]
Would really like to see signing for android from the CLI :+1:
